#!/bin/bash -e

cd $(dirname $0)

# Generate a new private key and Certificate Signing Request
# openssl req -sha256 -out root-ca.csr -new -newkey rsa:2048 -nodes -keyout root-ca.key -subj "/C=CN/ST=Shaanxi/L=Xi'an/O=ThoughtWorks, Inc./OU=AU/CN=ca.bqliu.com"
openssl genrsa -out root-ca.key 2048
# Generate a certificate signing request (CSR) for an existing private key
# openssl req -out root-ca.csr -key root-ca.key -new -subj "/C=CN/ST=Shaanxi/L=Xi'an/O=ThoughtWorks, Inc./OU=AU/CN=ca.bqliu.com" -sha256 -days 3650
# Generate a self-signed certificate
openssl req -x509 -sha256 -nodes -days 3650 -newkey rsa:2048 -keyout root-ca.key -out root-ca.crt -subj "/C=CN/ST=Shaanxi/L=Xi'an/O=ThoughtWorks, Inc./OU=AU/CN=ca.bqliu.com"
# Convert key to pem
openssl rsa -in root-ca.key -text > root-ca.key.pem
# Convert cert to pem
openssl x509 -inform PEM -in root-ca.crt > root-ca.crt.pem

# Generate a private key
openssl genrsa -out www.bqliu.com.key 2048
# Generate a Certificate Signing Request based on an existing certificate
# openssl x509 -x509toreq -in root-ca.crt -out www.bqliu.com.csr -signkey www.bqliu.com.key
openssl req -new -sha256 -key www.bqliu.com.key -subj "/C=CN/ST=Shaanxi/L=Xi'an/O=ThoughtWorks, Inc./CN=www.bqliu.com" -out www.bqliu.com.csr
# Generate a certificate based on CSR
openssl x509 -req -days 365 -sha256 -in www.bqliu.com.csr -CA root-ca.crt.pem -CAcreateserial -CAkey root-ca.key.pem -out www.bqliu.com.crt

# Check a Certificate Signing Request (CSR)
openssl req -text -noout -verify -in www.bqliu.com.csr
# Check a private key
openssl rsa -in www.bqliu.com.key -check
# Check a cert
openssl x509 -in root-ca.crt -text -noout
openssl x509 -in www.bqliu.com.crt -text -noout
# Check a PKCS#12 file (.pfx or .p12)
# openssl pkcs12 -info -in keyStore.p12


# https://www.sslshopper.com/article-most-common-openssl-commands.html
