#!/bin/bash -e

cd $(dirname $0)/..
source ./auto/config

cp certs/www.bqliu.com-chain.crt www/www.bqliu.com-chain.crt
cp certs/www.bqliu.com.key www/www.bqliu.com.key
docker build -t $WEB_IMAGE_NAME ./www
docker run \
  -d \
  -p 10000:80 \
  -p 443:443 \
  --name www-bqliu-com \
  $WEB_IMAGE_NAME
